### ISSUE TITLE
prediction

### ISSUE THREAD

**Issue by alem-memic** [XiSHEN0220/WatermarkReco#1]
Hello, I am a little bit confused here. I trained classification, obtained weights, but how am I going to use them for prediction? Is there any script for that? Some demo or something...

**Comment by XiSHEN0220** [comment]
Hi, @alem-memic ,

For the prediction of classification, you can directly do forward with model. 
Here is a pseudo code:

```
tensor = preprocessing (image)
pred = model.eval(tensor)
## pred will be with dimension 1, C, C is the number of classes
```

Or you could look into this [blog](https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html)
Hope it is clear.

Best, 

Xi
